//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSView.h"

@class NSCountedSet, NSMapTable, NSMutableDictionary;

@interface DVTLayoutView_ML : NSView
{
    NSCountedSet *_frameChangeObservations;
    NSCountedSet *_boundsChangeObservations;
    BOOL _implementsDrawRect;
    BOOL _implementsLayoutCompletionCallback;
    BOOL _layoutNeeded;
    NSMutableDictionary *_invalidationTokens;
    NSMapTable *_frameChangeStacksByView;
    NSMapTable *_boundsChangeStacksByView;
    BOOL _needsSecondLayoutPass;
}

+ (void)_doRecursivelyLayoutSubviewsOfView:(id)arg1 populatingSetWithLaidOutViews:(id)arg2 completionCallBackHandlers:(id)arg3 currentLayoutPass:(long long)arg4 needsSecondPass:(char *)arg5;
+ (void)_layoutWindow:(id)arg1;
+ (void)_recursivelyLayoutSubviewsOfView:(id)arg1 populatingSetWithLaidOutViews:(id)arg2;
+ (id)alreadyLaidOutViewsForCurrentDisplayPassOfWindow:(id)arg1;
+ (void)clearAlreadyLaidOutViewsForCurrentDisplayPassOfWindow:(id)arg1;
+ (void)scheduleWindowForLayout:(id)arg1;
//- (void).cxx_destruct;
- (void)_DVTLayoutView_MLSharedInit;
- (void)_autoLayoutViewViewBoundsDidChange:(id)arg1;
- (void)_autoLayoutViewViewFrameDidChange:(id)arg1;
- (void)_invalidateLayoutIfNeededAfterRegisteringRectChange:(struct CGRect)arg1 forView:(id)arg2 table:(id)arg3;
- (void)_reallyLayoutIfNeededBottomUp;
- (void)_reallyLayoutIfNeededTopDown;
- (void)_setupObservationForObservedObject:(id)arg1 selector:(SEL)arg2 notificationName:(id)arg3 observationCountTable:(id *)arg4 rectChangeStackTable:(id *)arg5;
- (void)_tearDownObservationForObservedObject:(id)arg1 notificationName:(id)arg2 observationCountTable:(id)arg3 rectChangeStackTable:(id)arg4;
- (void)dealloc;
- (void)didCompleteLayout;
- (void)didLayoutSubview:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)invalidateLayout;
- (void)invalidateLayoutWithBoundsChangesToView:(id)arg1;
- (void)invalidateLayoutWithChangesToKeyPath:(id)arg1 ofObject:(id)arg2;
- (void)invalidateLayoutWithFrameChangesToView:(id)arg1;
@property(getter=isLayoutNeeded) BOOL layoutNeeded; // @synthesize layoutNeeded=_layoutNeeded;
- (void)layoutBottomUp;
- (void)layoutIfNeeded;
- (void)layoutTopDown;
@property BOOL needsSecondLayoutPass; // @synthesize needsSecondLayoutPass=_needsSecondLayoutPass;
- (void)setFrameSize:(struct CGSize)arg1;
- (void)stopInvalidatingLayoutWithBoundsChangesToView:(id)arg1;
- (void)stopInvalidatingLayoutWithChangesToKeyPath:(id)arg1 ofObject:(id)arg2;
- (void)stopInvalidatingLayoutWithFrameChangesToView:(id)arg1;
- (id)subviewsOrderedForLayout;
- (void)viewDidMoveToWindow;
- (void)viewWillDraw;
- (BOOL)wantsDefaultClipping;

@end

