//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "IDEViewController.h"

@class DVTFindBar, DVTNotificationToken, DVTObservingToken, DVTScopeBarsManager, IDEEditorContext, IDEEditorDocument, IDEFileTextSettings, NSScrollView;

@interface IDEEditor : IDEViewController
{
    DVTFindBar *_findBar;
    DVTNotificationToken *_documentDidChangeNotificationToken;
    DVTNotificationToken *_documentForNavBarStructureDidChangeNotificationToken;
    DVTObservingToken *_documentFileURLObservingToken;
    BOOL _discardsFindResultsWhenContentChanges;
//    id <IDEEditorDelegate> _delegate;
    IDEEditorDocument *_document;
    IDEEditorDocument *_documentForNavBarStructure;
//    id <DVTTextFindable> _findableObject;
    IDEFileTextSettings *_fileTextSettings;
    IDEEditorContext *_editorContext;
}

+ (BOOL)canProvideCurrentSelectedItems;
//- (void).cxx_destruct;
- (id)_getUndoManager:(BOOL)arg1;
- (id)_initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)createFindBar;
- (id)currentSelectedDocumentLocations;
- (id)currentSelectedItems;
//@property(retain) id <IDEEditorDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didSetupEditor;
@property BOOL discardsFindResultsWhenContentChanges; // @synthesize discardsFindResultsWhenContentChanges=_discardsFindResultsWhenContentChanges;
@property(retain) IDEEditorDocument *document; // @synthesize document=_document;
@property(retain, nonatomic) IDEEditorDocument *documentForNavBarStructure; // @synthesize documentForNavBarStructure=_documentForNavBarStructure;
@property(retain) IDEEditorContext *editorContext; // @synthesize editorContext=_editorContext;
- (void)editorContextDidHideFindBar;
@property(retain, nonatomic) IDEFileTextSettings *fileTextSettings; // @synthesize fileTextSettings=_fileTextSettings;
@property(readonly) DVTFindBar *findBar; // @synthesize findBar=_findBar;
@property(readonly) BOOL findBarSupported;
//@property(retain, nonatomic) id <DVTTextFindable> findableObject; // @synthesize findableObject=_findableObject;
- (id)initUsingDefaultNib;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 document:(id)arg3;
@property(readonly, getter=isPrimaryEditor) BOOL primaryEditor;
@property(readonly) NSScrollView *mainScrollView;
- (void)navigateToAnnotationWithRepresentedObject:(id)arg1 wantsIndicatorAnimation:(BOOL)arg2 exploreAnnotationRepresentedObject:(id)arg3;
- (void)primitiveInvalidate;
- (id)relatedMenuItemsForNavItem:(id)arg1;
@property(readonly) DVTScopeBarsManager *scopeBarsManager;
- (void)selectDocumentLocations:(id)arg1;
- (void)setupContextMenuWithMenu:(id)arg1 withContext:(id)arg2;
- (id)supplementalTargetForAction:(SEL)arg1 sender:(id)arg2;
- (void)takeFocus;
- (id)undoManager;

@end

